### ISSUE TITLE
我运行graph_dta的训练脚本但是，卡住不动，运行结果如下

### ISSUE THREAD

**Issue by whz11** [PaddlePaddle/PaddleHelix#120]
graph_dta ❯ ./scripts/train.sh davis model_configs/fix_prot_len_gin_config.json
2021-06-11:22:51:55 [train.py:143] Load data ...
2021-06-11:22:51:55 [train.py:167] Data loaded.
2021-06-11:22:51:55 [train.py:182] ========== Epoch 0 ==========
/Users/apple/opt/anaconda3/envs/graph_dta/lib/python3.7/site-packages/paddle/nn/layer/norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")

**Comment by WorldEditors** [comment]
从你提供的信息看，训练并没有发生错误。这个Warning不影响训练。卡住会否是因为训练较慢？
建议减小数据确认下。如果还有问题，麻烦提供下完整的环境信息以便于验证。

建议PaddleHelix在训练过程中加入进度条提示。

**Comment by whz11** [comment]
> 从你提供的信息看，训练并没有发生错误。这个Warning不影响训练。卡住会否是因为训练较慢？
> 建议减小数据确认下。如果还有问题，麻烦提供下完整的环境信息以便于验证。
> 
> 建议PaddleHelix在训练过程中加入进度条提示。

谢谢你的回复，我训练一晚上，发现一个epoch要1小时左右，可能是数据集太大或者没有gpu的原因
