### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by 007goodmans** [PaddlePaddle/PaddleHelix#139]
Hello, many thanks for the toolset provided by the author. However, I had some problems with pre-training, the corresponding module could not be found in the author's file, for example, the 'from pahelix.model_zoo.pretrain_gnns_model import PretrainGNNModel, AttrmaskModel ' cannot find 'AttrmaskModel' and the 'from pahelix.featurizers.pretrain_gnn_featurizer import AttrmaskTransformFn, AttrmaskCollateFn' cannot find 'AttrmaskTransformFn, AttrmaskCollateFn'. I just came into contact with this training, may I ask how to solve this problem. With best wishes.

**Comment by Noisyntrain** [comment]
Hi, may I know what operating system you are using and are you running the code in our github project or just using our module to trian your own code? Thank you
