### ISSUE TITLE
SE(3) transformer implementation

### ISSUE THREAD

**Issue by riversdark** [PaddlePaddle/PaddleHelix#146]
Hi this might be a silly question, I noticed that SE(3) message passing is mentioned in the implemented networks but I couldn't find it. Can someone point me to the implementation?

Also a more general issue, I noticed that most of the network implementations have only a name, but no description of the detailed architectures, no use cases, and no documentation, so I'm having a bit difficulty getting started. Am I looking at the wrong places?

**Comment by SuperXiang** [comment]
Hi there, thanks for your interest. As for SE(3), we haven't officially released this part yet. Please keep following our latest update. And as for the second question, you can refer to our API documents(https://paddlehelix.readthedocs.io/en/dev/index.html) for more details and you can also make use of the tutorials(https://github.com/PaddlePaddle/PaddleHelix/tree/dev/tutorials) and notebooks on AI studio(https://aistudio.baidu.com/aistudio/personalcenter/thirdview/580918) for guidance.
