### ISSUE TITLE
请问你们能把alphafold2的BFD等3T序列数据下载到百度aistudio的公共数据集上，让大家都能使用百度aistudio做蛋白结构和复合物预测吗？

### ISSUE THREAD

**Issue by zihaoxingstudy1** [PaddlePaddle/PaddleHelix#190]
我觉得你们的PaddleHelix做的很好，百度aistudio上也有很多公开项目，但是没有现在特别火的alphafold的蛋白预测项目，请问你们能把alphafold2的BFD等3T序列数据下载到百度aistudio的公共数据集上，让大家都能使用百度aistudio做蛋白结构和复合物预测吗？

**Comment by Noisyntrain** [comment]
同学你好, 感谢你对PaddleHelix的支持, aistudio的数据集上传有着50G的大小限制, 因此我们正在上传BFD的一个18G的子集, 希望能对你有所帮助.

**Comment by zihaoxingstudy1** [comment]
> 同学你好, 感谢你对PaddleHelix的支持, aistudio的数据集上传有着50G的大小限制, 因此我们正在上传BFD的一个18G的子集, 希望能对你有所帮助.

哦哦，好的，这种公共数据集在服务器上只用上传一次就行了吧，大家都可以调用那一个数据集就行了

**Comment by Noisyntrain** [comment]
是的

**Comment by zihaoxingstudy1** [comment]
> 是的

嗯嗯，你们百度官方上传数据集的话，也是50G大小限制是吗

**Comment by Noisyntrain** [comment]
目前aistudio的公共数据集还只支持50g大小
