### ISSUE TITLE
关于使用XPU

### ISSUE THREAD

**Issue by EBGU** [PaddlePaddle/PaddleHelix#191]
您好！
我目前在使用百度昆仑的R200 XPU服务器， 我想了解一下HelixFold是否支持在XPU上训练和推理，谢谢！

**Comment by xiaoyao4573** [comment]
感谢对我们的关注，昆仑团队给我们反馈正在适配算子，有进一步消息会及时给你反馈。

**Comment by xiaoyao4573** [comment]
我们的团队尝试在XPU进行训练和推理，验证可以跑通，直接使用对应的包即可。

**Comment by EBGU** [comment]
> 

请问怎么set devices呀?
具体的说，我希望实现a）指定4张XPU种的某一张运行类似torch.device('cuda:0')这样 b）将一个长序列放到4张卡上跑（毕竟一张卡显存只有16GB）
以及XPU能跑OpenMM relax吗？

**Comment by zhxfl** [comment]
使用这个产出包替换原来的Paddle产出包即可使用单卡推理 wget https://baidu-kunlun-public.su.bcebos.com/KunlunPaddle/paddle-2.3-models/paddlepaddle_xpu-2.3.0-cp37-cp37m-linux_x86_64.whl
