### ISSUE TITLE
关于PaddleHelix/apps/drug_target_interaction/sign/项目中数据处理问题

### ISSUE THREAD

**Issue by tiezhuge** [PaddlePaddle/PaddleHelix#192]
在运行KDD 2021 paper: "Structure-aware Interactive Graph Neural Networks for the Prediction of Protein-Ligand Binding Affinity".这篇文章的代码数据处理部分命令行时
python preprocess_pdbbind.py --data_path_core YOUR_DATASET_PATH --data_path_refined YOUR_DATASET_PATH --dataset_name pdbbind2016 --output_path YOUR_OUTPUT_PATH --cutoff 5
出现了下图中的错误，不知该怎样解决，求助大佬
![image](https://user-images.githubusercontent.com/48878017/178106103-6db555ca-1890-451b-91d4-1d18e5452789.png)

使用的版本如下
Python 3.8.13 
paddlepaddle-gpu   2.3.1.post112

**Comment by agave233** [comment]
你好，这里的assert声明是为了保证对于读取的mol2文件已经去掉了其中的HOH，如果文件中本身没有的话就不用进行assert，在这里你可以删掉assert == 8这行代码来重新运行

**Comment by tiezhuge** [comment]
已解决问题，感谢您的回复！
