### ISSUE TITLE
模型权重

### ISSUE THREAD

**Issue by EBGU** [PaddlePaddle/PaddleHelix#194]
请问哪里可以下载模型权重呀 没有看到scripts/download_all_data.sh这个文件
谢谢！

**Comment by EBGU** [comment]
我目前在使用AF2提供的权重 请问有.pd的权重吗

**Comment by SuperXiang** [comment]
Hi，感谢您对HelixFold的兴趣和反馈。可以查看我们目前更新后的最新代码
