### ISSUE TITLE
helixfold模型运行时如何控制显存

### ISSUE THREAD

**Issue by TNTSAYou** [PaddlePaddle/PaddleHelix#196]
我按照helixfold的README_inference.md文件运行run_helixfold.py模型时遇到了显存溢出的问题，我使用的是一张12GB的3080Ti。我尝试降低batch的大小，但是看代码中batch似乎是要预测的蛋白质fasta文件的特征文件。所以有什么好的方法能够降低模型占用的显存容量吗，或者有其它能够帮助该模型在12G的显存上运行的建议吗？十分感谢您的帮助！！！！

**Comment by SuperXiang** [comment]
您好，感谢对HelixFold的兴趣和反馈。可以试试在config.py文件里修改并降低subbatch_size的大小，从而能inference更长蛋白

**Comment by TNTSAYou** [comment]
> 您好，感谢对HelixFold的兴趣和反馈。可以试试在config.py文件里修改并降低subbatch_size的大小，从而能inference更长蛋白

我试着把subbatch_size降低到12，发现还是内存溢出，我debug调试的时候发现似乎是数据处理的时候就已经溢出了，可能是我预测的蛋白序列太长了，我换了一个比较短的序列就可以预测了，还是感谢您的回答
