### ISSUE TITLE
ModuleNotFoundError: No module named 'pahelix.featurizers.gem_featurizer'

### ISSUE THREAD

**Issue by WeixuanXiong** [PaddlePaddle/PaddleHelix#202]
workspace /dfs/data/PaddleHelix/apps/pretrained_compound/ChemRL/GEM sh scripts/pretrain.sh
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "pretrain.py", line 34, in <module>
    from pahelix.featurizers.gem_featurizer import GeoPredTransformFn, GeoPredCollateFn
ModuleNotFoundError: No module named 'pahelix.featurizers.gem_featurizer'

error occurred when running pretrain.py

**Comment by WeixuanXiong** [comment]
problem solved

**Comment by zhangle-work** [comment]
Could you tell me how to solve it? Thanks
