### ISSUE TITLE
请问能走pickle不走搜索进行蛋白质结构预测吗

### ISSUE THREAD

**Issue by wangchenghaonl** [PaddlePaddle/PaddleHelix#209]

**Comment by wangchenghaonl** [comment]
feature_dict = data_pipeline.process(
            input_fasta_path=fasta_path,
            msa_output_dir=msa_output_dir)
        timings['features'] = time.time() - t0

        with open(features_pkl, 'wb') as f:
            pickle.dump(feature_dict, f, protocol=4)

    if args.distributed:
        dist.barrier()

    relaxed_pdbs, plddts = dict(), dict()
    for model_name, model_runner in model_runners.items():
        logger.info('Running model %s', model_name)

        input_features_pkl = output_dir.joinpath(f'{model_name}_input.pkl')



我注意到这里会把features_pkl导出，那这里的data_pipeline.process是否可以替换成pickle文件导入

**Comment by SuperXiang** [comment]
您好，我们代码里有两个关于features的.pkl文件，一个是raw features，一个是processed features，您是可以直接读取.pkl文件作为输入的，请参考`run_helixfold.py`的第91~110行。我们也提供了直接读取.pkl文件作为inference输入的demo，详细可参考[gpu_inference文档](https://github.com/PaddlePaddle/PaddleHelix/blob/dev/apps/protein_folding/helixfold/README_inference.md)

**Comment by wangchenghaonl** [comment]
好的还请问一下你们现在推理的最大支持长度是多少，我有一个长序列的任务想试验一下



---- 回复的原邮件 ----
| 发件人 | Yingfei(Jeremy) ***@***.***> |
| 日期 | 2022年08月25日 17:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleHelix] 请问能走pickle不走搜索进行蛋白质结构预测吗 (Issue #209) |

您好，我们代码里有两个关于features的.pkl文件，一个是raw features，一个是processed features，您是可以直接读取.pkl文件作为输入的，请参考run_helixfold.py的第91~110行。我们也提供了直接读取.pkl文件作为inference输入的demo，详细可参考gpu_inference文档

**Comment by SuperXiang** [comment]
目前GitHub上的开源版本在显存资源充足的前提下可以预测~2K+长度蛋白，你可以试试调整subbatch_size大小，切换至DAP、bf16模式等，我们后面会支持推理更长的蛋白，请保持关注

**Comment by wangchenghaonl** [comment]
好的那请问显存资源充足是A100吗因为我本地跑V100时大概1500序列长度就报内存不足了。

**Comment by SuperXiang** [comment]
你可以贴一下显卡的配置么？是V100 16G/32G/40G？我这边测过1500长度的蛋白序列用A100 40G应该是可以推理的哈

**Comment by wangchenghaonl** [comment]
V100 32G可以跑吗

**Comment by SuperXiang** [comment]
你试试只使用model_5配置，然后在[config.py](https://github.com/PaddlePaddle/PaddleHelix/blob/dev/apps/protein_folding/helixfold/alphafold_paddle/model/config.py)文件里设置subbatch_size=1

**Comment by wangchenghaonl** [comment]
好的多谢

**Comment by wangchenghaonl** [comment]
还有一个问题如果我用A100 40G是不是就可以跑2000+的序列，因为还有一条2000+长序列需要跑如果可以的话我去借一台A100 40G的机器

**Comment by SuperXiang** [comment]
CASP14长度为2180的T1044蛋白之前测试是可以跑的，更长的蛋白你可以试试，记得开启unified_memory和DAP，当然如果有更大显存的GPU更保险（如A100 80G）

**Comment by wangchenghaonl** [comment]
收到我去试验一下

**Comment by SuperXiang** [comment]
我先关闭issue了，如果后续有什么问题，可以随时打开
