### ISSUE TITLE
Use newer OpenMM

### ISSUE THREAD

**Issue by peastman** [PaddlePaddle/PaddleHelix#213]
The `setup_env` script pins OpenMM to 7.5.1, which is an old release that isn't supported anymore.  Could that be updated to the current release, or alternatively could the pin just be removed?  As far as I can tell nothing in the code requires the old version.

**Comment by SuperXiang** [comment]
Hi, thanks for the information. The pin to OpenMM is removed and the codes have been validated.

**Comment by peastman** [comment]
Thanks!
