### ISSUE TITLE
跑HelixFold-Single Inference demo时遇到问题

### ISSUE THREAD

**Issue by zytskymaker** [PaddlePaddle/PaddleHelix#216]
![image](https://user-images.githubusercontent.com/110749356/191449193-1429d736-e56a-4319-821b-7b701dc23b34.png)
![image](https://user-images.githubusercontent.com/110749356/191449234-fe7c0c32-2c0c-4f66-8c64-098ca28371f0.png)

**Comment by SuperXiang** [comment]
Hi there, thanks for your feedback. Could you provide more details about your environment, e.g., Paddle version?

**Comment by zytskymaker** [comment]
Python：3.7
CUDA 11.2,
cuDNN 8.0.5,
Ubuntu 18.04,
paddlepaddle-gpu 2.3.2

GPU：NVIDIA Tesla K80


| |
郑亦天
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Yingfei(Jeremy) ***@***.***> |
| 发送日期 | 2022年9月28日 16:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleHelix] 跑HelixFold-Single Inference demo时遇到问题 (Issue #216) |

Hi there, thanks for your feedback. Could you provide more details about your environment, e.g., Paddle version?

**Comment by SuperXiang** [comment]
The official PaddlePaddle 2.3.2 may not work for HelixFold-single. Please refer to [this page](https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html) for the suitable PaddlePaddle package.

**Comment by zytskymaker** [comment]
我改了paddle版本：
python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
然后出现了如下错误
| |
郑亦天
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Yingfei(Jeremy) ***@***.***> |
| 发送日期 | 2022年9月29日 11:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleHelix] 跑HelixFold-Single Inference demo时遇到问题 (Issue #216) |

The official PaddlePaddle 2.3.2 may not work for HelixFold-single. Please refer to this page for the suitable PaddlePaddle package.

**Comment by SuperXiang** [comment]
The log is missing. Would you please post the full error log?

**Comment by SuperXiang** [comment]
Close this issue for now. Please feel free to reopen if you have other questions later.
