### ISSUE TITLE
Question about the Branch Parallelism in Evoformer

### ISSUE THREAD

**Issue by zyeric** [PaddlePaddle/PaddleHelix#217]
Hi

I mention that you introduce branch parallelism in your arxiv paper. I wonder that is the model structure implemented by BP is identical to the one in Alphafold2 paper. It appears to me that computations are sequential in the paper.

Thanks!

**Comment by SuperXiang** [comment]
Hi there, thanks for your interest. Yes, we modify the model structure that does not affect the accuracy and the amount of calculations is equal to the original AF2 Evoformer block. Please keep following and the details will be made public soon.

**Comment by SuperXiang** [comment]
Hi, please refer to [our paper](http://arxiv.org/abs/2211.00235) for more details regarding BP.
