### ISSUE TITLE
`Model` object has no attribute decode in HelixFold

### ISSUE THREAD

**Issue by bernym12** [PaddlePaddle/PaddleHelix#218]
Stepped through this issue and I've found that `<simtk.openmm.app.internal.pdbstructure.Model object at 0x7f424e6f6750>` is passed in to this method within openmm that expects a file object. It is possible this is an openmm issue but this is currently blocking my usage of HelixFold. I have verified that I have the latest versions of both openmm and pdbfixer and also have recently pulled the updated `setup_env` file that made changes to the linking of openmm into simtek. 
```Traceback (most recent call last):                                                                                                                                                                  File "run_helixfold.py", line 375, in <module>                                                                                                                                                      main(args)                                                                                                                                                                                      File "run_helixfold.py", line 280, in main                                                                                                                                                          random_seed=random_seed)                                                                                                                                                                        File "run_helixfold.py", line 160, in predict_structure                                                                                                                                             output_dir, 0, timings)                                                                                                                                                                         File "/home/common/proj/FoldingBenchMarks/HelixFold/apps/protein_folding/helixfold/alphafold_paddle/model/model.py", line 283, in postprocess                                                       relaxed_pdb_str = relaxer.process(prot=prot)[0]                                                                                                                                                 File "/home/common/proj/FoldingBenchMarks/HelixFold/apps/protein_folding/helixfold/alphafold_paddle/relax/relax.py", line 63, in process                                                            max_outer_iterations=self._max_outer_iterations)                                                                                                                                                File "/home/common/proj/FoldingBenchMarks/HelixFold/apps/protein_folding/helixfold/alphafold_paddle/relax/amber_minimize.py", line 939, in run_pipeline                                             pdb_string = clean_protein(prot, checks=checks)                                                                                                                                                 File "/home/common/proj/FoldingBenchMarks/HelixFold/apps/protein_folding/helixfold/alphafold_paddle/relax/amber_minimize.py", line 187, in clean_protein                                            as_file = openmm_app.PDBFile(pdb_structure)                                                                                                                                                     File "/home/grads/bernardm/.conda/envs/helixfold/lib/python3.7/site-packages/simtk/openmm/app/pdbfile.py", line 96, in __init__                                                                     pdb = PdbStructure(inputfile, load_all_models=True, extraParticleIdentifier=extraParticleIdentifier)                                                                                            File "/home/grads/bernardm/.conda/envs/helixfold/lib/python3.7/site-packages/openmm/app/internal/pdbstructure.py", line 153, in __init__                                                            self._load(input_stream)                                                                                                                                                                        File "/home/grads/bernardm/.conda/envs/helixfold/lib/python3.7/site-packages/openmm/app/internal/pdbstructure.py", line 161, in _load                                                               if not isinstance(pdb_line, str):                                                                                                                                                             AttributeError: 'Model' object has no attribute 'decode'```

**Comment by SuperXiang** [comment]
Hi there, thanks for the feedback. Could you try using openmm==7.5.1 as before or predicting the structure without relaxation?

**Comment by bernym12** [comment]
Thank you for getting back to me so soon. That appears to have resolved my issue.
