### ISSUE TITLE
pip install paddlehelix

### ISSUE THREAD

**Issue by sightsIndeep** [PaddlePaddle/PaddleHelix#221]
ERROR: No matching distribution found for paddlehelix

**Comment by SuperXiang** [comment]
Hi there, thanks for your interest. Would you provide more details of your system and environment?

**Comment by sightsIndeep** [comment]
windows 10, Anaconda 2.3.2

**Comment by SuperXiang** [comment]
You can refer to [installation guide](https://github.com/PaddlePaddle/PaddleHelix/blob/dev/installation_guide.md) or [developer guide](https://github.com/PaddlePaddle/PaddleHelix/blob/dev/developer_guide.md) for more installation details.

**Comment by sightsIndeep** [comment]
![图片](https://user-images.githubusercontent.com/3212951/195022059-3a04dbf8-1f65-419e-a70b-287b8ba797ad.png)

**Comment by SuperXiang** [comment]
Please try modifying the path of `pip` with regards to `anaconda` or run `python3 -m pip install` instead of `pip install`

**Comment by SuperXiang** [comment]
Close this issue for now. Please feel free to reopen if you have other questions later.

**Comment by quantaosun** [comment]
pip install not working
```
ERROR: Could not find a version that satisfies the requirement paddlehelix (from versions: none)
ERROR: No matching distribution found for paddlehelix
```
