### ISSUE TITLE
paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl 这个包安装在AMD EPYC 7742平台上发生指令集异常

### ISSUE THREAD

**Issue by xiamr** [PaddlePaddle/PaddleHelix#230]
https://baidu-nlp.bj.bcebos.com/PaddleHelix/HelixFold/paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl 这个包安装在AMD EPYC 7742平台上发生指令集异常
`Python 3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Illegal instruction (core dumped)`

**Comment by SuperXiang** [comment]
Hi，这个Paddle包需在特定系统环境下才能使用，暂不支持AMD架构，详情参考[使用文档](https://github.com/PaddlePaddle/PaddleHelix/blob/dev/apps/protein_folding/helixfold/README_train.md)，后续Paddle官方包升级发布后可支持，请保持关注
