### ISSUE TITLE
GEM 数据处理很慢

### ISSUE THREAD

**Issue by 545487677** [PaddlePaddle/PaddleHelix#240]
你好，我想问一下，当我使用你们的GEM方法进行数据处理的时候，他处理的非常慢，请问有什么可以加速的方法嘛？
具体代码如下
 dataset = InMemoryDataset(data_list)
dataset.transform(DownstreamTransformFn())

**Comment by 545487677** [comment]
谢谢

**Comment by Noisyntrain** [comment]
Hi, 545487677, you can add the num_workers arg to accelerate the data processing.
https://github.com/PaddlePaddle/PaddleHelix/blob/850a594719359f86fd0c7f71e6175387ca40b0bc/apps/pretrained_compound/ChemRL/GEM/finetune_class.py#L161
But you need to pay attention to the RAM and cpu usage when using multi-workers. If too many workerers are used, it may cause the some problems.
