### ISSUE TITLE
Could you please provide the CASP14 test set which you evaluated on?

### ISSUE THREAD

**Issue by JoeyL12138** [PaddlePaddle/PaddleHelix#252]
I understand that the CASP14 proteins are available from the CASP website, but I wasn't sure which of the proteins that you kept for test evaluation. Could you please provide the CASP14 test set which you evaluated on? Thanks!

**Comment by SuperXiang** [comment]
Hi, 

Thanks for the interest. We use the same 87 domain targets for CASP14 evaluation which is mentioned in [supplementary information for AlphaFold2](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03819-2/MediaObjects/41586_2021_3819_MOESM1_ESM.pdf). Please refer to 1.12.2 for the details.

**Comment by JoeyL12138** [comment]
Thanks for the answer！
