### ISSUE TITLE
加载GEM pretrain model提示模型shape和权重shape不一致

### ISSUE THREAD

**Issue by wjybill** [PaddlePaddle/PaddleHelix#274]
你好，我在加载geognn模型预训练权重（位置在PaddleHelix/apps/pretrained_coumpound/ChemRL/GEM/pretrain_models/class.pdparams）的时候显示有两个layes的权重大小匹配不上，分别是 init_atom_embedding.embed_list.3 和 init_atom_embedding.embed_list.6。如下图所示 

![image](https://github.com/PaddlePaddle/PaddleHelix/assets/67458283/a3a39ea4-6336-4afc-9f16-1a20619b3165)

另外还有一个问题，如果想手动修改geognn模型中的每层的节点数量应该如何操作呢？

**Comment by Noisyntrain** [comment]
Hi wjybill, 权重的问题应该是由于rdkit的版本不同导致的，你可以试试更早期的rdkit-pypi版本(比如2022.3.1)。每层的节点数量具体指的是什么呢？节点数应该是和输入分子的原子数相等的
