### ISSUE TITLE
Hydra configuration for HelixFold3 

### ISSUE THREAD

**Issue by YaoYinYing** [PaddlePaddle/PaddleHelix#319]
Hi Paddle team, 

First of all, thanks for this wonderful program!
I have a [branch](https://github.com/YaoYinYing/PaddleHelix) that  help HF3 configurable with Hydra and I am not sure if it can help people working better with it. 

If you guys find this branch is cool and worth a PR, I would be appreciated to create one.

Regards,
Yinying

**Comment by RyanGarciaLI** [comment]
Hi Yinying,

We greatly appreciate your constructive contribution to our work. Configuration via `yaml` indeed improves our code compatibility and makes our model more user-friendly. We will follow our roadmap and consider merging this feature in our next released version. Again, thanks for your engagement. We hope you’ll continue to share your insights with us!

Best regards,
Ryan LI
Paddle Team
