### ISSUE TITLE
Any Ideas about Covalent bond btw ligand and protein residue?

### ISSUE THREAD

**Issue by YaoYinYing** [PaddlePaddle/PaddleHelix#323]
I would like to add some features like creating covalent bond between input ligand and protein atom(with similar way of treating leaving groups from protein like rosettafold-all-atom) or harmonic distance constraints from one to anther in order to mimic such bonding info. Any ideas?

**Comment by RyanGarciaLI** [comment]
Hi,

Our opensource model doesn't directly support covalent bond input, but you may create an input adapter to implement it. 
Firstly, please refer to a `cif` [file](https://files.rcsb.org/view/4K3P.cif ) with covalent bonds and find out `asym_id`, `seq_id`, `atom_id` for all covalent connections. Next, try to put those features into `make_bond_features()` in `./helixfold/data/pipeline_conf_bonds.py`. This function explains how HelixFold3 integrates with covalent bond features.

Thanks

**Comment by YaoYinYing** [comment]
@RyanGarciaLI Thanks so much for this message you provided! I have implemented this function in my branch and it looks good to me! 

<img width="524" alt="image" src="https://github.com/user-attachments/assets/47de2e5a-e413-42df-aa98-d44bedc361e8">
