### ISSUE TITLE
Clarify HelixFold3 license

### ISSUE THREAD

**Issue by agitter** [PaddlePaddle/PaddleHelix#326]
The HelixFold3 [copyright](https://github.com/PaddlePaddle/PaddleHelix/tree/dev/apps/protein_folding/helixfold3#copyright) statement says that code and model weights are available under the CC BY-NC-SA license. However, the link to the full [license](https://github.com/PaddlePaddle/PaddleHelix/blob/dev/apps/protein_folding/helixfold3/LICENSE) is not the CC BY-NC-SA license but rather a custom license.

If the custom license is the applicable license, it would be easier to understand the readme by removing the CC BY-NC-SA reference. Creative Commons does not recommend their licenses for [software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) anyway.

**Comment by xiaoyao4573** [comment]
We fixed it. Thanks for your suggestions.
