### ISSUE TITLE
On the issue of Scripts bash commands

### ISSUE THREAD

**Issue by LUDENGZHEN** [PaddlePaddle/PaddleHelix#327]
The files downloaded in the download_helixfold3_checkpoints.sh script are in zip format and should be extracted using unzip, not tar.

**Comment by LUDENGZHEN** [comment]
![微信图片_20240828112246](https://github.com/user-attachments/assets/6bf4ae70-342a-4675-9ff3-4daa8721a110)

**Comment by RyanGarciaLI** [comment]
Hi,

Thank you for your suggestions. We have updated our download script. Thanks for your contributions again.

PaddleHelix Team
Ryan LI
