### ISSUE TITLE
CUDA and cuDNN version mismatch HelixFold3

### ISSUE THREAD

**Issue by ahmedselim2017** [PaddlePaddle/PaddleHelix#341]
Hi, the environment part of the readme for the HelixFold3 suggests that CUDA 12.0 should be installed alongside cuDNN 8.40. However, the cuDNN archive of Nvidia (https://developer.nvidia.com/rdp/cudnn-archive) has cuDNN 8.4.0 only for CUDA 10.2 and 11.x. The first cuDNN release that supports CUDA 12 is cuDNN 8.8. Should the CUDA version that supports cuDNN 8.4.0 or the cuDNN version that supports CUDA 12 be used?

**Comment by RyanGarciaLI** [comment]
Hi, sorry for the unclear content in the README. You may choose CUDA 12 with cuDNN 8.9 or CUDA 11.x with cuDNN 8.4. You can select any combination of CUDA/cuDNN versions that Paddle 2.6.1 supports. Thanks.

**Comment by ahmedselim2017** [comment]
Thank you very much!
