### ISSUE TITLE
Carboxyl terminus of the protein lacks an oxygen atom.

### ISSUE THREAD

**Issue by Garhorne0813** [PaddlePaddle/PaddleHelix#345]
Hi! I noticed that in every test case, **the carboxyl terminus of the protein is missing an oxygen atom.**

Here’s an example from the demo case **demo_8ecx.**

[](url)
![8F835DD6-86D1-4d4c-8387-5FBC0CB9F1FF](https://github.com/user-attachments/assets/05af38af-e2a2-4292-a7f8-c8bd540eab6b)

**Comment by leaves520** [comment]
Hi, @Garhorne0813. Thank you for your detailed testing and feedback. We has fixed it, please see the new commit: 
https://github.com/PaddlePaddle/PaddleHelix/pull/350.
The followed example is look good now: 
![image](https://github.com/user-attachments/assets/98d1e225-1118-4032-8d37-563f1e21ee8c)
We look forward to more feedback from you to improve our work ! Thanks !
