### ISSUE TITLE
Error in HelixFold3: ref_atom_name_chars < 64

### ISSUE THREAD

**Issue by ebettler** [PaddlePaddle/PaddleHelix#353]
Hello,
i'm working with Helixfold3 for virtual screening between a protein and a list of ligands. For some ligands, i've the error:
File "/softwares/helixfold/3/PaddleHelix/apps/protein_folding/helixfold3/helixfold/data/pipeline_conf_bonds.py", line 111, in make_ccd_conf_features
    assert np.max(features['ref_atom_name_chars']) < 64

Is there any limitation in ligand features ?

Thanks for your job !!

BR,

**Comment by leaves520** [comment]
@ebettler Hello, can you show me your json file? This helps us locate and fix the problem. 🤝

**Comment by ebettler** [comment]
Here is just one example:
{
    "entities": [
        {
            "type": "protein",
            "sequence": "MFADRWLFSTNHKDIGTLYLLFGAWAGVLGTALSLLIRAELGQPGNLLGNDHIYNVIVTAHAFVMIFFMVMPIMIGGFGNWLVPLMIGAPDMAFPRMNNMSFWLLPPSLLLLLASAMVEAGAGTGWTVYPPLA
GNYSHPGASVDLTIFSLHLAGVSSILGAINFITTIINMKPPAMTQYQTPLFVWSVLITAVLLLLSLPVLAAGITMLLTDRNLNTTFFDPAGGGDPILYQHLFWFFGHPEVYILILPGFGMISHIVTYYSGKKEPFGYMGMVWAMMSIGFLGFIVWAHH
MFTVGMDVDTRAYFTSATMIIAIPTGVKVFSWLATLHGSNMKWSAAVLWALGFIFLFTVGGLTGIVLANSSLDIVLHDTYYVVAHFHYVLSMGAVFAIMGGFIHWFPLFSGYTLDQTYAKIHFTIMFIGVNLTFFPQHFLGLSGMPRRYSDYPDAYTT
WNILSSVGSFISLTAVMLMIFMIWEAFASKRKVLMVEEPSMNLEWLYGCPPPYHTFEEPVYMKS",
            "count": 1
        },
        {
            "type": "ligand",
            "smiles": "Clc1c(Nc2c(CC(O)=O)cccc2)c(Cl)ccc1",
            "count": 1
        }
    ]
}

**Comment by leaves520** [comment]
Hi, @ebettler , we get the expected output from your input json.

**Comment by leaves520** [comment]
Hi, @ebettler , we get the expected output from your input, please use the latest code of our branch.
![image](https://github.com/user-attachments/assets/c7ee442a-fa85-4fb5-9804-796ef1d1008c)

**Comment by ebettler** [comment]
Cool ! It works !! Thanks !!
