### ISSUE TITLE
HelixDock: 请问可否提供下helix dock预训练对接数据中的蛋白质结构部分

### ISSUE THREAD

**Issue by fengshikun** [PaddlePaddle/PaddleHelix#354]
您好，之前通过联系飞桨的工作人员，获得了helix dock的预训练docking数据，但是发现只有ligand部分的结构(mol2)文件，没有pocket或者protein的结构信息，请问可否也提供一下蛋白结构的信息，感谢！
<img width="731" alt="image" src="https://github.com/user-attachments/assets/afd09bbb-5537-41c4-aeb9-b664234962a2">

**Comment by Noisyntrain** [comment]
Hi 感谢对PaddleHelix的关注和支持，在开放的同bucket下的all_pdb_processed_tared 文件夹储存了所有的蛋白结构信息以及口袋位点，通过bos下载解压bos:/helixdock-open-data/all_pdb_processed_tared 即可获取。希望能解决您的问题 :)
