### ISSUE TITLE
有中文版的API文档吗

### ISSUE THREAD

**Issue by jiushinakecai** [PaddlePaddle/PaddleHelix#68]
有中文版的API文档吗

**Comment by xiaoyao4573** [comment]
API文档我们暂时不考虑提供中文版本的，因为API文档主要是通过工程师通过添加使用方法的注释通过工具自动生成。
但是我们的Tutorial教程和Readme说明文档都是同时提供中英文两个版本的。
如果同学对API文档有不明白的地方欢迎提issue～

**Comment by jiushinakecai** [comment]
哦 好的
